# Generated by Django 4.1.7 on 2023-03-30 19:34

import django.db.models.deletion
from django.db import migrations, models

import core.services.uppload_car_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='photo',
        ),
        migrations.CreateModel(
            name='CarPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=core.services.uppload_car_service.upload_to)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.carmodel')),
            ],
            options={
                'db_table': 'car_photos',
            },
        ),
    ]
