# Generated by Django 4.1.7 on 2023-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=20)),
                ('product_year', models.IntegerField()),
                ('place_count', models.IntegerField()),
                ('body_type', models.CharField(max_length=20)),
                ('engine_volume', models.FloatField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
