# Generated by Django 4.1.7 on 2023-03-30 12:11

from django.db import migrations, models

import core.services.uppload_car_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_photo_alter_carmodel_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.uppload_car_service.upload_to),
        ),
    ]
