# Generated by Django 4.1.7 on 2023-03-30 19:34

from django.db import migrations, models

import core.services.uppload_profile_service


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.uppload_profile_service.upload_to),
        ),
    ]
